version: "3.3"

services:
  app:
    build: .
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - "3300:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./mysql_init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=admin


    